# Generated by Django 2.2.7 on 2019-12-02 11:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Timelines',
            },
        ),
    ]
