# Generated by Django 2.2.7 on 2019-12-02 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webdings', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Timeline',
            new_name='Event',
        ),
    ]
