# Generated by Django 2.2.7 on 2019-12-04 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webdings', '0003_auto_20191204_1437'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.TextField()),
                ('email', models.CharField(max_length=200)),
                ('body', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Guests',
            },
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('person_responsible', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Notes',
            },
        ),
        migrations.CreateModel(
            name='Shortlists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.TextField()),
                ('supplier', models.CharField(max_length=200)),
                ('cost', models.TextField()),
                ('contact', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Shortlists',
            },
        ),
    ]
