# Generated by Django 2.2.7 on 2019-12-04 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webdings', '0004_guests_notes_shortlists'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shortlists',
            new_name='Supplier',
        ),
    ]
