# Generated by Django 2.2.7 on 2019-12-04 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webdings', '0006_auto_20191204_1613'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplier',
            options={'verbose_name_plural': 'Suppliers'},
        ),
    ]
