# Generated by Django 2.2.7 on 2019-12-04 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webdings', '0007_auto_20191204_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='category',
            field=models.TextField(choices=[('Flowers', 'Flowers'), ('Cake', 'Cake'), ('Venue', 'Venue'), ('Catering', 'Catering'), ('Decor', 'Decor'), ('Beauty', 'Beauty'), ('Music', 'Music'), ('Photos', 'Photography'), ('Transport', 'Transport'), ('Favours', 'Favours')]),
        ),
    ]
