# Generated by Django 2.2.7 on 2019-12-04 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webdings', '0008_auto_20191204_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='cost',
            field=models.IntegerField(),
        ),
    ]
