# Generated by Django 2.2.7 on 2019-12-04 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webdings', '0010_board'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aim', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name_plural': 'Aims',
            },
        ),
        migrations.RenameField(
            model_name='board',
            old_name='link',
            new_name='board',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='body',
        ),
    ]
